name: trlAi
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pip:
      - transformers
      - datasets
      - evaluate
      - tensorboard
      - huggingface_hub
      - accelerate
      - sacrebleu
      - sentencepiece
