name: trlAi
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10.12
  - pip>=23.3.1
  - setuptools>=68.0.0
  - wheel>=0.40.0
  - numpy>=1.26.0
  - pandas>=2.0.0
  - scipy>=1.6.0
  - scikit-learn>=1.3.0
  - pytorch>=2.1.0
  - pyarrow>=15.0.0
  - grpcio>=1.48.2
  - lxml>=5.4.0
  - pip:
      - datasets>=2.14.4
      - evaluate>=0.4.0
      - dynaconf>=3.2.0
      - tensorboard>=2.14.0
      - huggingface_hub>=0.17.3
      - filelock>=3.12.2
      - fsspec>=2023.9.2
      - pyyaml>=6.0.1
      - requests>=2.32.3
      - tqdm>=4.65.0
      - transformers>=4.35.0
      - sacrebleu>=2.3.1
      - psycopg2-binary>=2.9.6
      - accelerate>=0.27.0
      - sentencepiece>=0.1.99
